import type { ItemDef, ItemId } from "./types";

export const ITEMS: Record<ItemId, ItemDef> = {
  rusty_knife: {
    id: "rusty_knife",
    name: "무딘 단도",
    desc: "평민이 쥐는 짧은 날.",
    slot: "weapon",
    atk: 2,
    weaponLook: "dagger",
  },
  ember_blade: {
    id: "ember_blade",
    name: "잔광검",
    desc: "성문 근처에서 벼려진 직검.",
    slot: "weapon",
    atk: 6,
    weaponLook: "sword",
  },
  twin_edge: {
    id: "twin_edge",
    name: "쌍날검",
    desc: "가벼운 베기용 세장검.",
    slot: "weapon",
    atk: 5,
    weaponLook: "saber",
  },
  glow_staff: {
    id: "glow_staff",
    name: "잔광 지팡이",
    desc: "끝을 밝히는 시전자의 지팡이.",
    slot: "weapon",
    atk: 5,
    mp: 6,
    weaponLook: "staff",
  },
  shrine_rod: {
    id: "shrine_rod",
    name: "성소 홀",
    desc: "짧은 홀. 온기를 담는다.",
    slot: "weapon",
    atk: 4,
    hp: 6,
    weaponLook: "rod",
  },
  wool_cape: {
    id: "wool_cape",
    name: "양모 망토",
    desc: "외곽 바람막이.",
    slot: "cape",
    def: 1,
    capeLook: "short",
  },
  dusk_cape: {
    id: "dusk_cape",
    name: "잔광 망토",
    desc: "석양빛을 머금은 천.",
    slot: "cape",
    def: 2,
    hp: 4,
    capeLook: "royal",
  },
  iron_helm: {
    id: "iron_helm",
    name: "무쇠 투구",
    desc: "코받이가 짧은 투구.",
    slot: "helm",
    def: 3,
    helmLook: "helm",
  },
  hide_coat: {
    id: "hide_coat",
    name: "가죽 웃옷",
    desc: "들판용 겹옷.",
    slot: "body",
    def: 2,
    bodyLook: "coat",
  },
  ironward_plate: {
    id: "ironward_plate",
    name: "철갑판",
    desc: "철갑감시자의 흉갑 조각.",
    slot: "body",
    atk: 2,
    def: 5,
    hp: 10,
    bodyLook: "plate",
  },
  slime_gel: {
    id: "slime_gel",
    name: "슬라임 겔",
    desc: "문지르면 상처가 덜하다.",
    slot: "use",
    heal: 14,
  },
  ember_flask: {
    id: "ember_flask",
    name: "잔광 물약",
    desc: "온기를 들이킨다.",
    slot: "use",
    heal: 32,
  },
  mana_tea: {
    id: "mana_tea",
    name: "안개차",
    desc: "시야가 맑아진다.",
    slot: "use",
    restoreMp: 20,
  },
  wolf_fang: {
    id: "wolf_fang",
    name: "늑대 송곳니",
    desc: "거래용 이빨.",
    slot: "misc",
  },
  shade_dust: {
    id: "shade_dust",
    name: "그늘 가루",
    desc: "차갑게 반짝인다.",
    slot: "misc",
  },
  bandit_coin: {
    id: "bandit_coin",
    name: "노획 동전",
    desc: "길에 떨어진 잔화.",
    slot: "gold",
    gold: 8,
  },
};

export function itemName(id: ItemId): string {
  return ITEMS[id].name;
}
